### PR TITLE
Added Hebrew names

### LINKED ISSUE #8: Add Hebrew Names and Surnames
The repository is missing **Hebrew names and surnames**. Follow the guide below to add them.

## 🚀 How to Contribute:

1. **Fork** the repository.
2. **Add** names and surnames for your country following the format provided below.
3. **Submit** a Pull Request with your changes.
4. Please **include a reliable source** for the names and surnames you're adding, preferably a public database or a reputable website.

## 📄 Format:

For names (`src/names/il.ts`):

```typescript
const hebrewNames = {
    0: [ // Male names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ],
    1: [ // Female names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ]
}

export default hebrewNames;
```

For surnames (`src/surnames/il.ts`):

```typescript
const hebrewSurnames = [ // Add the URL of the surnames source here
    'Surname1', 'Surname2', 'Surname3', ...
];

export default hebrewSurnames;
```

## 📌 Important Notes:

- Ensure that the names and surnames you add are common and not specific to a small group.
- 50 names for both males and females, and 50 surnames.
- Organize the names with 10 entries per row.
- Avoid adding names that might be offensive or inappropriate.
- Ensure you're not violating any copyright or data privacy rules.

### PR DESCRIPTION
**Pull request by Tashuuuu**
Fixes #8

### CODE REVIEW

**Comment by ozdemirburak** [comment]
Thanks for the PR. However, the names provided are transliterated. For instance, the Hebrew name should be אברהם, not Abraham.

**Comment by Tashuuuu** [comment]
Then shouldn't the Indian names be in Hindi? I only saw that PR and did accordingly

**Comment by ozdemirburak** [comment]
You can send a PR for Indian names as well. I'm not that sure about how most Indians prefer to write their names online in Devanagari or transliterated.

**Comment by Tashuuuu** [comment]
Isn't Indian names issue already closed? And Indiana write their names in many languages like Tamil, Punjabi, Bengali, etc. But mostly in Hindi and English

**Comment by ozdemirburak** [comment]
The issue being closed doesn't mean that the file can't be improved. Anyway, I'm going to accept these, then will edit.

**Comment by Tashuuuu** [comment]
Got it. Thank you

**Pull request merged**
